version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10.0
    deployment:
      #environment:
      dockerhub:
        branch: livetest
        commands: -$DOCKER_HUB_TRIGGER
  second_job:
    - run: 
        command: echo "hello world"
    - hold:
          type: approval

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
